name: Create Release & Push Package & v5
on:
  push:
    tags: 
      - v5*

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: npm install
    - run: npm run hoist

    - run: npm run build
    - run: npm run coverage

    - run: npm run b:website
    - run: npm run b:doc

    - run: cp -rp LICENSE packages/uiw

    - run: |
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        COMMIT=released-${VERSION}
 
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        echo "version: $VERSION"
        export VERSION

        node node_modules/.bin/lerna version $VERSION --no-changelog --no-git-tag-version --no-push --yes --force-publish
        npm run b:website
        npm run b:doc
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .

        git commit -am $COMMIT

    - run: rm -rf packages/doc/web
    - run: mkdir -p packages/doc/web

    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      with:
        filter-author: (renovate\[bot\]|actions-user|renovate-bot|dependabot\[bot\])
        output: ./website/build/CONTRIBUTORS.svg
        avatarSize: 42

    - run: cp -rf website/build/* packages/doc/web

    - run: npm run bundle
    - run: cp -rp packages/uiw/dist/*js website/build
    - run: cp -rp packages/uiw/dist/*css website/build

    - run: git checkout -f packages/uiw/tsconfig.json

    - run: git status

    - name: git push v5
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: v5

    - name: get tag version
      id: tag_version
      uses: jaywcjlove/changelog-generator@v1.5.0

    - name: Create README.md
      working-directory: ./website/build
      run: |
        cat > README.md << EOF
        Documentation uiw@v5
        ====

        Preview: https://raw.githack.com/uiwjs/uiwjs.github.io/v5/index.html
        EOF

    - name: Deploy to uiwjs.github.io Repo
      uses: peaceiris/actions-gh-pages@v3
      with:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: '[${{steps.tag_version.outputs.tag}}] ${{ github.event.head_commit.message }}'
        personal_token: ${{ secrets.PERSONAL_TOKEN_UIW }}
        publish_dir: ./website/build
        publish_branch: v5
        external_repository: uiwjs/uiwjs.github.io

    - name: Generate changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.5.0
      with:
        filter-author: (å°å¼Ÿè°ƒè°ƒâ„¢)
        filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)

    - run: |
        echo "tag: ${{ steps.changelog.outputs.tag }}"
        echo "version: ${{ steps.changelog.outputs.version }}"
        echo "ref: ${{ github.ref }}"

    # - name: Create Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     name: ${{ steps.changelog.outputs.tag }}
    #     tag: ${{ steps.changelog.outputs.tag }}
    #     body: |
    #       [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/uiw@${{steps.changelog.outputs.version}}/file/README.md) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/uiw)](https://bundlephobia.com/result?p=uiw@${{steps.changelog.outputs.version}}) [![npm version](https://img.shields.io/npm/v/uiw.svg)](https://www.npmjs.com/package/uiw)
          
    #       Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/uiwjs/uiwjs.github.io/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html
    #       Comparing Changes: ${{ steps.changelog.outputs.compareurl }}

    #       ```bash
    #       npm i uiw@${{steps.changelog.outputs.version}}
    #       ```

    #       ${{ steps.changelog.outputs.changelog }}


    - name: ðŸ“¦ @uiw/react-affix publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/react-affix/package.json
        tag: bate
    - name: ðŸ“¦ @uiw/react-alert publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/react-alert/package.json
        tag: bate
    - name: ðŸ“¦ @uiw/react-auto-link publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-auto-link/package.json
        tag: bate
    - name: ðŸ“¦ @uiw/react-avatar publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-avatar/package.json
    - name: ðŸ“¦ @uiw/react-back-top publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-back-top/package.json
    - name: ðŸ“¦ @uiw/react-badge publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-badge/package.json
    - name: ðŸ“¦ @uiw/react-breadcrumb publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-breadcrumb/package.json
    - name: ðŸ“¦ @uiw/react-button publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-button/package.json
    - name: ðŸ“¦ @uiw/react-button-group publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-button-group/package.json
    - name: ðŸ“¦ @uiw/react-calendar publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-calendar/package.json
    - name: ðŸ“¦ @uiw/react-card publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-card/package.json
    - name: ðŸ“¦ @uiw/react-carousel publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-carousel/package.json
    - name: ðŸ“¦ @uiw/react-cascader publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-cascader/package.json
    - name: ðŸ“¦ @uiw/react-checkbox publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-checkbox/package.json
    - name: ðŸ“¦ @uiw/react-collapse publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-collapse/package.json
    - name: ðŸ“¦ @uiw/react-copy-to-clipboard publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-copy-to-clipboard/package.json
    - name: ðŸ“¦ @uiw/react-date-input publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-date-input/package.json
    - name: ðŸ“¦ @uiw/react-date-picker publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-date-picker/package.json
    - name: ðŸ“¦ @uiw/react-descriptions publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-descriptions/package.json
    - name: ðŸ“¦ @uiw/react-divider publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-divider/package.json
    - name: ðŸ“¦ @uiw/react-drawer publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-drawer/package.json
    - name: ðŸ“¦ @uiw/react-dropdown publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-dropdown/package.json
    - name: ðŸ“¦ @uiw/react-empty publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-empty/package.json
    - name: ðŸ“¦ @uiw/react-file-input publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-file-input/package.json
    - name: ðŸ“¦ @uiw/react-form publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-form/package.json
    - name: ðŸ“¦ @uiw/react-grid publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-grid/package.json
    - name: ðŸ“¦ @uiw/react-icon publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-icon/package.json
    - name: ðŸ“¦ @uiw/react-input publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-input/package.json
    - name: ðŸ“¦ @uiw/react-list publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-list/package.json
    - name: ðŸ“¦ @uiw/react-loader publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-loader/package.json
    - name: ðŸ“¦ @uiw/react-menu publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-menu/package.json
    - name: ðŸ“¦ @uiw/react-message publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-message/package.json
    - name: ðŸ“¦ @uiw/react-modal publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-modal/package.json
    - name: ðŸ“¦ @uiw/react-month-picker publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-month-picker/package.json
    - name: ðŸ“¦ @uiw/react-notify publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-notify/package.json
    - name: ðŸ“¦ @uiw/react-overlay publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-overlay/package.json
    - name: ðŸ“¦ @uiw/react-overlay-trigger publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-overlay-trigger/package.json
    - name: ðŸ“¦ @uiw/react-pagination publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-pagination/package.json
    - name: ðŸ“¦ @uiw/react-pin-code publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-pin-code/package.json
    - name: ðŸ“¦ @uiw/react-popover publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-popover/package.json
    - name: ðŸ“¦ @uiw/react-portal publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-portal/package.json
    - name: ðŸ“¦ @uiw/react-progress publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-progress/package.json
    - name: ðŸ“¦ @uiw/react-radio publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-radio/package.json
    - name: ðŸ“¦ @uiw/react-rate publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-rate/package.json
    - name: ðŸ“¦ @uiw/react-search-select publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-search-select/package.json
    - name: ðŸ“¦ @uiw/react-search-tree publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-search-tree/package.json
    - name: ðŸ“¦ @uiw/react-select publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-select/package.json
    - name: ðŸ“¦ @uiw/react-slider publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-slider/package.json
    - name: ðŸ“¦ @uiw/react-steps publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-steps/package.json
    - name: ðŸ“¦ @uiw/react-switch publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-switch/package.json
    - name: ðŸ“¦ @uiw/react-table publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-table/package.json
    - name: ðŸ“¦ @uiw/react-tabs publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-tabs/package.json
    - name: ðŸ“¦ @uiw/react-tag publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-tag/package.json
    - name: ðŸ“¦ @uiw/react-textarea publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-textarea/package.json
    - name: ðŸ“¦ @uiw/react-time-picker publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-time-picker/package.json
    - name: ðŸ“¦ @uiw/react-tooltip publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-tooltip/package.json
    - name: ðŸ“¦ @uiw/react-tree publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-tree/package.json
    - name: ðŸ“¦ @uiw/react-tree-checked publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-tree-checked/package.json
    - name: ðŸ“¦ @uiw/react-transfer publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/react-transfer/package.json
    - name: ðŸ“¦ @uiw/utils publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/utils/package.json
    - name: ðŸ“¦ @uiw/uiw publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/uiw/package.json
    - name: ðŸ“¦ @uiw/doc publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        tag: bate
        package: ./packages/doc/package.json
