name: Build uiw
on:
  push:
    branches:
      - master
jobs:
  build-uiw:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - run: npm install
    - run: npm run bootstrap

    # - run: npm run build
    - run: npm run b:uiw
    - run: npm run b:css
    - run: npm run type

    - run: npm run hoist
    - run: npm run b:website
    - run: npm run b:doc

    - run: npm run bundle
    - run: npm run coverage